import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";

const sourceSans3 = Poppins({
  subsets: ["latin"],
  weight: ["400","500", "600", "700","800"], // regular (400), semiBold (600)
  variable: "--font-source-sans-3",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceSans3.variable} scrollbar-none`}
      >
        {children}
      </body>
    </html>
  );
}
